### ISSUE TITLE
How to admin?

### ISSUE THREAD

**Issue by hundhest** [nate-strauser/wework#105]
How do I enable admin functions?

**Comment by hundhest** [comment]
I figured it out.. Learning so much playing around with this,. Many thanks

**Comment by nate-strauser** [comment]
Great!  Sorry I didn't get back to you in time.

**Comment by hundhest** [comment]
No problem. I am learning a lot by trying out our your framework here. Thank you.

**Comment by justinxreese** [comment]
I think this should be re-opened as an actual issue to add documentation for how to add an admin. I have no clue how to do this and the comments unfortunately did not lead to anything.

**Comment by justinxreese** [comment]
For anyone that finds this thread in the future: the answer is to add an `adminEmails: ['your@email.address'],` setting to the `AdminConfig` var in `both/admin.js`

**Comment by nate-strauser** [comment]
Feel free to submit a pull request to change the readme file.  We can add
notes there.  Probably need a link to the yogiben:admin package too as that
has all the admin usage documentation.

**Comment by justinxreese** [comment]
Actually, my instructions are wrong because if you sign up for an account with twitter there seems to be no email address tied to that?

**Comment by justinxreese** [comment]
@nate-strauser would you consider posting the wework `admin.js` with credentials omitted so I could see what you're doing? the instructions on the yogiben package also don't really explain what they're doing and I think there is some application logic involved with adminining (they reference posts being a thing in their example app)

**Comment by nate-strauser** [comment]
it's already available :)

https://github.com/nate-strauser/wework/blob/master/both/admin.js

the yogiben admin package will make the very first user that goes to /admin
an admin.  I just use that mechanism to make my own account the first
admin.  Works well enough for weworkmeteor.  In the past I have specified
emails as shown in docs to make users be admins.

All you really need is 1 admin user, then you can make other admins from
that.  That is how you could make your twitter based account be an admin.
