### ISSUE TITLE
Job posts not featured after payment success?

### ISSUE THREAD

**Issue by justinxreese** [nate-strauser/wework#108]
I'm wondering if I could get some insight into what could cause this to fail.

The stripe payments on my site at http://jobs.abstractions.io are going through, but I have to manually add a "Featured Through" date to each one to get them to be featured.

Not sure where to look. Any help greatly appreciated. It's okay for now, but I'm going to be using this for our upcoming conference and won't have time to manually feature posts during the event.

**Comment by nate-strauser** [comment]
That sounds pretty strange.  Are you sure the charges are going through?
Do you see them in the stripe control panel?

This is the code that does the charging -
https://github.com/nate-strauser/wework/blob/master/both/lib/methods.js#L94
- you should either get an error or the job should be marked as featured,
another outcome isn't really possible

**Comment by justinxreese** [comment]
Yes. Definitely have charges. Just refunded three of them because the user was confused and kept trying. I'll look at the referenced method here in a bit.

**Comment by justinxreese** [comment]
No errors in app logs

**Comment by justinxreese** [comment]
Actually there are errors in the app console, didn't show up in Galaxy

`Blocked a frame with origin "https://checkout.stripe.com" from accessing a frame with origin "https://jobs.abstractions.io". Protocols, domains, and ports must match.` is shown early in the process and when I attempt to make a payment it inserts an error

`Insert Error: – n {stack: "n@https://jobs.abstractions.io/e8[REDACTED]2cf.js?meteor_js_resource=true:50:17769", error: "Payment Failed!", reason: undefined, …}`

**Comment by nate-strauser** [comment]
i made a small change to output a better error condition - try that out and let me know what it says now

it seems like the stripe charge may be going through, but that the response is not as expected, thus the job is not marked as featured

**Comment by justinxreese** [comment]
Cool that's nice. I'll give it a shot. We looked at the stripe API and noticed it might respond with "pending" instead of "succeeded". Will let you know

**Comment by nate-strauser** [comment]
hmm - i guess that could be it - i've only ever gotten back 'succeeded' in
my testing

the charge checking logic could be `status !== 'failed'`, but that leaves
me concerned about what happens if a 'pending' status later turns into
'failed'.

**Comment by swans-one** [comment]
@nate-strauser I've been working on this, and we've actually been receiving a status of `'paid'`. This is in disagreement with their Documentation here: https://stripe.com/docs/api#charge_object-status but it is what we're seeing.

Changing line 101 here: https://github.com/nate-strauser/wework/blob/master/both/lib/methods.js#L101

to:

```
	        if(result && (result.status === "succeeded" || result.status === "paid")){
```

Solves this issue.
