### ISSUE TITLE
How to Work Admin Panel?

### ISSUE THREAD

**Issue by aboobakkar** [nate-strauser/wework#114]
How to work this App [admin]( https://github.com/yogiben/meteor-admin) in this app ? 

> http://localhost:3000/admin  is just show 

> You need to be an admin to view this page

**Comment by nate-strauser** [comment]
the admin package is https://atmospherejs.com/yogiben/admin - all
configuration and usage of the admin panel is specific to that package

either the first user to go to /admin will become an admin or you can
manually specify emails of admins in the config
