### ISSUE TITLE
Compact job ofers and profiles

### ISSUE THREAD

**Issue by Elfoslav** [nate-strauser/wework#18]
As a user, I want to see job position titles first, when the title is interesting, then I want to see more, usually open it in new tab. http://www.weworkmeteor.com/jobs listing is too long. It should have compact view like on this page http://www.startupjobs.cz/ The same with profiles.

Also notice logos of companies on Startupjobs. Companies can differ from other companies with their logos. Expert profiles should contain profile pictures too.

**Comment by nate-strauser** [comment]
i think this was covered with the recent update - let me know if you have any other suggestions
