### ISSUE TITLE
Allow profiles to upload a custom image

### ISSUE THREAD

**Issue by nate-strauser** [nate-strauser/wework#21]

**Comment by jorisbontje** [comment]
maybe atleast explain them how to set it up?

> if you signed up using a password based account, set up gravatar.com for that email address if you signed up with a social service (twitter, facebook, google, github) then set your profile image on that service

**Comment by nate-strauser** [comment]
i think i need to add a user profile page where users can set/change their email address - then we could have all avatars be able to fall back to gravatar -- right now, if you signed up with a meteor developer account, i don't get an image or an email, so it's just the default ghost

**Comment by nate-strauser** [comment]
going to do image upload with uploadcare - should be live soon

**Comment by nate-strauser** [comment]
![image](https://cloud.githubusercontent.com/assets/389646/6517209/cc48e996-c366-11e4-97bb-f10b85ff6e8b.png)
![image](https://cloud.githubusercontent.com/assets/389646/6517242/18897f0a-c367-11e4-9727-21327a8c7c6c.png)
![image](https://cloud.githubusercontent.com/assets/389646/6517250/212e65bc-c367-11e4-9455-2e8b712e6df8.png)
![image](https://cloud.githubusercontent.com/assets/389646/6517254/2a6e5704-c367-11e4-8d1a-70b03b9d0697.png)


so the profile now defaults to the auto avatar, if a custom image is uploaded that will be displayed instead

uploadcare worked pretty well for this - was a little easier than what i've done with filepicker in the past
