### ISSUE TITLE
Use summernote autoform plugin to allow wysiwyg editing

### ISSUE THREAD

**Issue by nate-strauser** [nate-strauser/wework#23]
https://atmospherejs.com/mpowaga/autoform-summernote

replace the description/htmlDesciption fields with just 'description' that stores html - add a migration task to move this data over

**Comment by dandv** [comment]
I much prefer Markdown because I can paste my resume from Careers.SO or MeteorPedia etc. MeteorGigs uses a WYSIWYG editor and I have to manually reconstruct the links.

**Comment by nate-strauser** [comment]
of course i just spent the past few hours getting WYSIWYG working nicely  :/

i think that developers are probably ok with markdown, but my concern was
mainly for job posters - aka non-technical folks - wysiwig should appeal to
them much more

**Comment by nate-strauser** [comment]
@dandv you think it would be good enough if i give you a code/html view?  should be able to copy paste from other sites then.

**Comment by nate-strauser** [comment]
deploying now - code view is active
