### ISSUE TITLE
Admin dashboard isn't showing Jobs / Experts

### ISSUE THREAD

**Issue by jorisbontje** [nate-strauser/wework#25]
The `Jobs` and `Experts` collections on the admin dashboard will always show 0 entries, even though there are multiple ones created and visible on the homesite.

**Comment by nate-strauser** [comment]
apparently this is a known bug with the admin package
https://github.com/yogiben/meteor-admin/issues/124

once that is fixed, i'll update the version and it should work

**Comment by nate-strauser** [comment]
downgraded to v1.0.9 - seems to work now
