### ISSUE TITLE
Request to delete/merge profile; couldn't add photo

### ISSUE THREAD

**Issue by dandv** [nate-strauser/wework#40]
I signed up with my Meteor account and created a profile at `www.weworkmeteor.com/experts/2faYNc8rCfJQ642To` but there was no way to add a photo to it.

Today I signed up again with GitHub, but the two profiles aren't linked. I've since beefed up my [new profile](http://www.weworkmeteor.com/experts/CKc8SWQYPzLqMTw3d).

Does it matter how long ago a profile has been on the site? If so, can you please add merge the new one into the old one, or add a photo?

Otherwise, could you please delete the old one? Thanks!

**Comment by nate-strauser** [comment]
deleted!

i also am currently working on a way to set an image for any login type -
sorry for the trouble

**Comment by dandv** [comment]
Thanks!
