### ISSUE TITLE
Job page points to create profile instead of editing the current one

### ISSUE THREAD

**Issue by dandv** [nate-strauser/wework#41]
Is this intended? At http://www.weworkmeteor.com/jobs/3NusBANwSupKANgXM I see a link to Create developer profile even though I already have one. Is this intended for resume targeting? How can I access all my profiles?

I ended up creating `http://www.weworkmeteor.com/experts/DbttnoXpzfhKKNKwZ` to reproduce the bug.

**Comment by nate-strauser** [comment]
this is a bug that i have fixed in the version i'm working on now - i'll
confirm it is resolved before deployment

**Comment by nate-strauser** [comment]
fixed with recent deployment

**Comment by dandv** [comment]
I can still edit two profiles - http://www.weworkmeteor.com/profiles/CKc8SWQYPzLqMTw3d (good one, let's keep it)

`weworkmeteor.com/profiles/DbttnoXpzfhKKNKwZ` - test, can we please delete? Thanks!

**Comment by nate-strauser** [comment]
deleted - looking good now?
