### ISSUE TITLE
De-activating jobs

### ISSUE THREAD

**Issue by ianserlin** [nate-strauser/wework#50]
[Feature Request]

I have a job posting on weworkmeteor that I would like to inactivate for now, however we hire fairly often and usually the same template with a few changes.

Some kind of option to archive and then de-archive or archive and then re-post (as a copy) of a job would be awesome vs simply delete.

**Comment by nate-strauser** [comment]
i'm thinking that i could just remove the hard delete completely - having users deactivate/suspend instead

**Comment by ianserlin** [comment]
Works for me, especially since you're not charging, no biggie. :)

-------
Ian Serlin
ian@ianserlin.com
415-754-9563
http://twitter.com/spiceninja
http://www.linkedin.com/in/ianserlin

**Comment by rkstar** [comment]
hi @nate-strauser is there a way to do this yet?  i can't figure out how to suspend or delete a posting.

**Comment by nate-strauser** [comment]
Yes! - You should see this when looking at your post

![image](https://cloud.githubusercontent.com/assets/389646/13438051/4470559c-dfb5-11e5-847e-5b1f6da0d187.png)

**Comment by rkstar** [comment]
i don't.  [i just see edit here](https://www.weworkmeteor.com/jobs/HN63H5H6M4n92TYef/developer-needed-to-help-with-debugging-and-bug-fixes-mixed-pay-and-equity)

<img width="286" alt="screen shot 2016-03-01 at 1 57 31 pm" src="https://cloud.githubusercontent.com/assets/651566/13438132/a7d64772-dfb5-11e5-9a4f-863fd44cffda.png">

**Comment by nate-strauser** [comment]
you sure you didn't already deactivate this job?  it's currently set to
'inactive' status, looks like that happened last tuesday.

job does not appear in listings, but is still accessible via the url

i'll add a message to the job indicating this status

**Comment by rkstar** [comment]
i thought i had deactivated it, but i am still getting emails.  i guess the fact that it's still available via the url is why that's happening.

i've added messaging to the post.

maybe you could add a feature that will throw a banner across the top, or just not show the post if it's deactivated.

**Comment by nate-strauser** [comment]
filled/inactive jobs now have a banner

![image](https://cloud.githubusercontent.com/assets/389646/13439627/5f91578e-dfbc-11e5-97b3-c589b1cf0425.png)


could totally hide the job to anyone but the owner in the future if needed
