### ISSUE TITLE
Modal shadow disables any action

### ISSUE THREAD

**Issue by dandv** [nate-strauser/wework#51]
I've just logged in with my Meteor account and can't seem to be able to do anything. My user profile pic was gone and I wanted to log in and re-upload. This is what I see in Chrome:

![image](https://cloud.githubusercontent.com/assets/33569/6980576/e9475e4e-d9a8-11e4-97a5-cda1cf0613c5.png)

**Comment by jorisbontje** [comment]
@dandv thanks for reporting! I have created a PR to fix this.
