### ISSUE TITLE
new installation error

### ISSUE THREAD

**Issue by awrelll** [nate-strauser/wework#54]
Hello,
I cloned the repo on a Ubuntu 14 environment and i get this error when i try to start the app 

```
Not migrating, already at version 5
Restivus configured at api/ without authentication
{"line":"52","file":"synced-cron-server.js","message":"SyncedCron: scheduled \"Randomize Profile Random Sorter\" next run @Wed Apr 22 2015 16:00:00 GMT+0000 (UTC)","time":{"$date":1429716292165},"level":"info"}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)
```

Can anyone help me please ?

Thanks

**Comment by jorisbontje** [comment]
@awrelll most likely you already have a Meteor process running on port 3000 (`ethereum.builders` maybe?) Either kill it or run the wework process on a different port using `meteor --port 4000`

**Comment by awrelll** [comment]
@jorisbontje hey ! this was deployed on a new server.  i can see the app on port 3000 in development but my bundled app won't start. 
Thanks !

**Comment by awrelll** [comment]
Solved. Nginx was causing some troubles. Thanks !
