### ISSUE TITLE
Dropdown menu on logged in user doesn't work on responsive toggle menu

### ISSUE THREAD

**Issue by jamc92** [nate-strauser/wework#69]
![meteor-toggle-dropdown-responsive-menu-bug](https://cloud.githubusercontent.com/assets/1733996/8398251/a9dc82e2-1db0-11e5-83c7-0b2092c55997.png)

**Comment by nate-strauser** [comment]
this looks like it might be a good fix - https://github.com/geedmo/yamm3

**Comment by edionmelarosa** [comment]
This is fixed on my PR.

**Comment by nate-strauser** [comment]
thanks!
