### ISSUE TITLE
Where do you put the Uploadcare Secret key?

### ISSUE THREAD

**Issue by tizol** [nate-strauser/wework#78]
setting-example.json
```json
"uploadcare":{
      "publickey": "xxxxxxxxxxxxxxxxxxx",

    }
```

**Comment by nate-strauser** [comment]
the secret key is not needed as no server side calls are made to uploadcare.  it's all done with the publickey from the client.

**Comment by tizol** [comment]
I did put my publickey. But I get this error "natestrauser_uploadcare-plus.js: 73 uploadcare-plus - tried to load but key not supplied".

**Comment by nate-strauser** [comment]
Are you running the app with '--settings' specified and pointing to your
settings file?
