### ISSUE TITLE
Where is search function?

### ISSUE THREAD

**Issue by daveeel** [nate-strauser/wework#79]
Can't find such function. Is search function planned?

**Comment by nate-strauser** [comment]
currently there is no search, but it is planned for developers/profiles

**Comment by ritchieng** [comment]
+1

**Comment by pddew** [comment]
+1

**Comment by hafizali05** [comment]
@nate-strauser I have implemented search in my last project and technically this is my first ever open source contribution if I am allowed to start search using easysearch.

**Comment by nate-strauser** [comment]
i'm not sure that easysearch will be viable with the existing infinite scroll behavior

probably just need to do plain mongo full text searching
see https://www.okgrow.com/posts/guide-to-full-text-search-in-meteor

see https://github.com/nate-strauser/wework/blob/master/server/publications.js#L231
https://github.com/nate-strauser/wework/blob/master/client/views/profiles/profiles.js#L2
slightly customized version of infinite scroll package - https://github.com/nate-strauser/wework/tree/master/packages/meteor-infinite-scroll

--

i'm not opposed to easy search, but i do like the infinite scrolling, which doesnt seem to work with easysearch
https://github.com/matteodem/meteor-easy-search/search?q=infinite&type=Issues&utf8=%E2%9C%93

**Comment by nate-strauser** [comment]
@hafizali05 i implemented basic searching.  you could extend it with a PR if you want (searching for other attributes).  getting it to work with infinite scrolling was a little tricky.

**Comment by hafizali05** [comment]
@nate-strauser   would love to do that, thanks :)
