### ISSUE TITLE
Add "Upload Picture" functionality

### ISSUE THREAD

**Issue by Ulydev** [nate-strauser/wework#82]
Hello,

Thanks for sharing this project! I'm just starting out with Meteor and this has greatly helped me.

I'd like to implement an "Upload Picture" feature in the Developer Profile editor, but I'm not sure where to start. Could you please help me and point me some directions?

Thanks,
Ulysse

**Comment by nate-strauser** [comment]
What type of picture did you have in mind?  The profiles already support
uploading a custom user avatar via uploadcare.com.

**Comment by Ulydev** [comment]
I'd just like to upload simple jpg/png pictures.
The thing is, I set up an uploadcare.com account and added the key in settings.json, but there's no option  to upload images in the profile editor. Am I missing something?

https://i.gyazo.com/2da3143a610a03cd3ac00b0f0dd736d0.png

**Comment by nate-strauser** [comment]
for some reason it isn't working for you

on weworkmeteor.com you get
![image](https://cloud.githubusercontent.com/assets/389646/12488523/fd562a3c-c039-11e5-8c2d-3d6354e538b9.png)

the 'choose an image' button opens the uploadcare widget
![image](https://cloud.githubusercontent.com/assets/389646/12488536/0f65f9b4-c03a-11e5-881d-d01f8bdab82e.png)

**Comment by Ulydev** [comment]
I forgot this part. https://github.com/nate-strauser/wework/issues/78#issuecomment-165929620

Thanks for helping, and keep up the awesome work!

**Comment by nate-strauser** [comment]
Great!
