### ISSUE TITLE
Image Upload Issue

### ISSUE THREAD

**Issue by ritchieng** [nate-strauser/wework#85]
Hi,

I've successfully set up everything with UploadCare's public key. 

However, I do not have the "choose an image" and I can't figure out why. Thanks for your help!

**Comment by nate-strauser** [comment]
Without any details, I'm assuming you actually did not set up uploadcare
correctly.  Probably missing the setting or not running with the settings
included.  If set up correctly, it will be there when editing a profile.

**Comment by ritchieng** [comment]
Hi,

Thanks for your prompt reply, really appreciate it. 

I placed the public key under the settings.json file

I do have some messages when I ran meteor though, but everything else is running fine. Here you go.

"W20160219-17:44:06.436(1)? (STDERR) Astronomer settings not found in Meteor.settings, skipping setup.
I20160219-17:44:06.438(1) (percolatestudio_synced-cron.js:60) SyncedCron: scheduled "Randomize Profile Random Sorter" next run @Fri Feb 19 2016 17:44:06 GMT+0100 (CET)
I20160219-17:44:06.439(1) (percolatestudio_synced-cron.js:60) SyncedCron: scheduled "Prerender.io Recache Main Pages" next run @Fri Feb 19 2016 17:44:06 GMT+0100 (CET)
I20160219-17:44:06.449(1) (migrations_server.js:82) Migrations: Not migrating, already at version 6
"

**Comment by nate-strauser** [comment]
did you run it with 'meteor --settings your-settings-file.json'?

**Comment by ritchieng** [comment]
Oh yes it works for local host. However when I use mupx deploy I get this error:

154.5sevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)

**Comment by ritchieng** [comment]
It works now, I had issues with the settings.json file as you've mentioned. 

In case anyone who're unsure:

1. Fill up the details in the settings-example.json file

2. Copy over to your settings.json file outside of the your applications folder where you initiate mupx. By default it's empty so you must make sure it's not empty. 

3. mupx setup then mupx deploy to make everything work!

**Comment by nate-strauser** [comment]
Great!
