### ISSUE TITLE
Account Signup Help

### ISSUE THREAD

**Issue by ritchieng** [nate-strauser/wework#86]
Hi,

Currently users:
1. Create Account
2. Change Username when they log in. 

However, may I know if users are able to key in their usernames during the sign-up process? Really appreciate the help on this because now by default it uses their email and the "update username" option after signing up is not intuitive. 

Thanks!

**Comment by nate-strauser** [comment]
We could have password based accounts set the username at sign up, but
oauth accounts can't do this.  To have the same approach for all accounts,
we could pop up an onboarding modal after sign up to capture the username.
Same basic functionality that exists now, just automatically presented to
the user after sign up.

**Comment by ritchieng** [comment]
@nate-strauser Thanks for your recommendation. Any idea how do I go about to automatically present it to the user? Thanks, just starting out.

**Comment by nate-strauser** [comment]
could do something like this

```
Tracker.autorun(function() {
        var user = Users.findOne({
            _id: Meteor.userId()
        }, {
            fields: {
                "profile.name": 1
            }
        });
        if (user && (!user.profile || !user.profile.name)) {
               Modal.show('userProfile');
        }
    });
```

**Comment by ritchieng** [comment]
Thanks for your help. Which file should I be placing this?

**Comment by nate-strauser** [comment]
probably /client/autorun.js

**Comment by ritchieng** [comment]
There's the following error.
```
I20160303-17:55:23.483(1)? Exception while invoking method 'ATCreateUserServer' { stack: 'ReferenceError: Modal is not defined\n    at AccountsServer._onCreateUserHook (server/accounts.js:13:1)\n    at AccountsServer.Ap.insertUserDoc (accounts_server.js:1230:21)\n    at createUser (password_server.js:980:25)\n    at AccountsServer.Accounts.createUser (password_server.js:1049:10)\n    at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/lib/server_methods.js:103:1)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at livedata_server.js:708:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:706:40\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:704:46\n    at tryCallTwo (/Users/xx/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)\n    at doResolve (/Users/xx/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)\n    at new Promise (/Users/xx/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)\n    at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)',
I20160303-17:55:23.483(1)?   source: 'method' }

```

**Comment by nate-strauser** [comment]
you can't open a client side modal from server code - onCreateUser is not
the right spot for this

**Comment by ritchieng** [comment]
Thanks for guiding me through so far. 

I don't get that "onCreateUser" is not the right spot. I placed it in /client/autorun.js. Does it have to do with adding something to accounts.js?

**Comment by nate-strauser** [comment]
the error is saying that you are trying to load a modal from
server/accounts.js

**Comment by ritchieng** [comment]
Ok! So this code would not work? It's not an issue of whether I placed it in both or client because I tried both.

**Comment by nate-strauser** [comment]
i'm sorry but this is not a problem with the app as i've written it, its something custom you are trying to do with your own fork - so i'm closing this issue

that code i supplied will work to load a client side modal, i use it in other production apps - it can not run on the server - if that doesn't help you, you are on your own to resolve this

**Comment by ritchieng** [comment]
Hey @nate-strauser. I just wanted to tell you it works. Really thankful. I left a line of code in the server/accounts.js file that caused issues. 

So if anyone wants a modal that pops up after they log in, this is an excellent code to be placed in client/autorun.js!

**Comment by nate-strauser** [comment]
Great!
