### ISSUE TITLE
Unable to Delete Users

### ISSUE THREAD

**Issue by ritchieng** [nate-strauser/wework#89]
There's a bug in yogiben's admin for this. When you try to delete the user, the modal keeps on auto closing.

**Comment by nate-strauser** [comment]
i can't seem to find the yogiben issue for this - can you supply the link to the issue?

**Comment by ritchieng** [comment]
Hi,

You can head to www.reviw.me/admin using the following credentials:

ritchie_ng@hotmail.com
ritchie

**Comment by ritchieng** [comment]
@nate-strauser No idea if this is useful for you or anyone. But I managed to solve the issue of modal continuously closing after removing a package nemo64:bootstrap. 

This is because the modal plugin JS loads twice. I hope it helps anyone out there!
