### ISSUE TITLE
Router Slug Undefined 

### ISSUE THREAD

**Issue by ritchieng** [nate-strauser/wework#91]
Hi,

This is what happens for profile if user do not key in "Title" field where they get name-undefined: 
http://localhost:3000/#!profiles/ei5rHwB9XatnwngCC/john-undefined

May I know how do I get rid of the "-undefined" in the URL? Thanks!

**Comment by nate-strauser** [comment]
the title is required, so how did you get this?

you could change how the slug is calculated -
https://github.com/nate-strauser/wework/blob/master/both/collections/profiles.js#L179

i don't think this is an issue with the default functionality, so i'm
closing this issue.

**Comment by ritchieng** [comment]
Thanks @nate-strauser. Very helpful.
