### ISSUE TITLE
How to disable job post disappearing? 

### ISSUE THREAD

**Issue by ritchieng** [nate-strauser/wework#94]
Hi,

Currently job posts disappear after a certain number of days (90). How do we disable it and make it permanently there? Thanks.

**Comment by nate-strauser** [comment]
remove the 'createdAt' part of the find here https://github.com/nate-strauser/wework/blob/master/server/publications.js#L135

**Comment by ritchieng** [comment]
Thanks @nate-strauser. Always helping!
