### ISSUE TITLE
How to auto-approve job posts?

### ISSUE THREAD

**Issue by ritchieng** [nate-strauser/wework#95]
Hi,

When the number of job posts increase, it would be easier to approve them first by default. May I know do I do that? Thanks!

**Comment by nate-strauser** [comment]
just change this https://github.com/nate-strauser/wework/blob/master/both/collections/jobs.js#L85 to return 'active' instead of 'pending'

**Comment by ritchieng** [comment]
Thanks again @nate-strauser.
