### ISSUE TITLE
scroll back to position

### ISSUE THREAD

**Issue by thomasspiesser** [nate-strauser/wework#97]
Hey Nate,
I got a bit tired of scrolling down to position X when I used the browsers back button, so I tried to fix it. This isn't as easy as I thought it would be with Meteor and so I didn't submit a PR just yet. Here is the code though if you wanna give it a spin. The code goes in `router.js`.

```javascript
// Start: save scroll position.

if ( Meteor.isClient ) {
    var backToPosition;
    var scrollPosition;
    window.onpopstate = function() {
        backToPosition = scrollPosition;
    };
    var IRHooks = {
        scrollUp: function() {
            $('body,html').animate({
                scrollTop: backToPosition || 0
            }, 300 );
            backToPosition = undefined;
            this.next();
        },
        saveScrollPosition: function() {
            scrollPosition = $(window).scrollTop();
        }
    };
    Router.onRun( IRHooks.scrollUp );
    Router.onStop( IRHooks.saveScrollPosition );
}

// End: save scroll position.
```

It does the job locally but I'm unsure about the timing when there is a bit more latency involved. Let me know what you think.
Cheers,
Thomas

**Comment by nate-strauser** [comment]
i think this package - https://atmospherejs.com/okgrow/router-autoscroll -
does basically this

i've tried to use that before but it never quite worked right for me

have you tried this on the jobs/profile listing pages that have infinite
scrolling?  i'm curious if that just works by setting the scroll position
or if you'd have increment the page count to get it working.

**Comment by thomasspiesser** [comment]
Yes, that's where the idea came from, but they do a lot more so I took out the important bit. If it never worked right for you, just ignore it. It is a bit of a headache with meteor unfortunately. cheers
