### ISSUE TITLE
Failure in some versions of chrome.

### ISSUE THREAD

**Issue by gunn** [nate-strauser/wework#98]
The main pages of the site do not render due to an error:
```
Exception in callback of async function: Error: Handler with name 'u' already exists.
```
API etc. still working fine.

**Comment by nate-strauser** [comment]
Was this the main site weworkmeteor.com or something else?  Site seems fine
to me.  Still happening?

Seems like there was an galaxy infrastructure upgrade rollout during around
when this was submitted.  Maybe a passing effect of that.
http://status.meteor.com/

**Comment by gunn** [comment]
The main site. Experimenting more though, it seems to be a browser issue. It's failing to render for me on chrome 51 (multiple computers) but working fine on firefox and older chrome versions.

**Comment by nate-strauser** [comment]
hmmm - chrome 50.0.2661.86 is the latest i get on my mac and it seems to
work

please share any further details - thanks!

**Comment by gunn** [comment]
Versions `51.0.2704.22 beta (64-bit)` and `51.0.2687.0 dev (64-bit)`. I don't really know what I can add - I've already tried incognito sessions and disabling all extensions. Could login status be affecting it?

**Comment by cloudzombie** [comment]
Same happened for me on Chrome mobile, but works on chrome desktop just fine in a development stage fork.

**Comment by nate-strauser** [comment]
very odd - still working fine for me on latest desktop + mobile chrome

**Comment by nate-strauser** [comment]
i found this http://stackoverflow.com/questions/36356403/error-after-update-to-meteor-1-3-handler-with-name-onbeforeaction-already-ex which sounds very close to what is being reported - updated packages to attempt fix, hopefully that does it

**Comment by grsabreu** [comment]
I'm having the same issue here

**Comment by grsabreu** [comment]
Just checked again and everything is normal!

**Comment by nate-strauser** [comment]
great! closing this then.
